theme: readthedocs
site_url: https://seatunnel.eshop88.cn
site_name: SeaTunnel中文文档
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
    indexing: 'full'
nav:
- 主页: index.md
- 快速开始: quickstart.md
- Config: config.md
- Source: 
  - 支持源: source/source-v2.md
  - Http: source/connector-http.md