theme: 
  name: readthedocs
  include_sidebar: false
site_url: https://seatunnel.eshop88.cn
site_name: SeaTunnel中文文档
site_description: Apache SeaTunnel 是一个分布式、高性能、易扩展、用于海量数据（离线&实时）同步和转化的数据集成平台。
copyright: Copyright &copy; 2023.
nav:
- 阿里云务器99元: https://www.aliyun.com/minisite/goods?userCode=m87ienyv
- 主页: index.md
- 快速开始: quickstart.md
- Config: config.md
- Source: 
  - 支持源: source/source-v2.md
  - Http: source/connector-http.md
  - Kafka2Mysql: source/kafka2mysql.md